function [packets] = create_packet(npack)
%Create_packet function create packets for main flow
%               
%       Input : npack - number of packets to create
%
%       Output : packets - the packets generated by the function
%                          the size is [npack x packetSize]

%set the packet size, this is set according to the simulcast paper
%after the 
packetSize = 923;

%generate a random packet with fixed length 
packets = boolean(round(rand(npack, packetSize)));


end